apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-007
  name: nginx-007
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-007
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx-007
    spec:
      containers:
      - image: nginx
        name: nginx-007
        resources: {}
status: {}
